DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
  "id" VARCHAR(255) UNiQUE NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);